package Login;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author CASPER
 */
public class LoginPage extends javax.swing.JFrame {
    
    Connection conn=null;
    
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form login
     */
    public LoginPage() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setBackground(new Color(0, 0, 0, 0));
        textUserName.setBackground(new Color(0, 0, 0, 0));
        textPassword.setBackground(new Color(0, 0, 0, 0));
        
        ImageIcon img = new ImageIcon(getClass().getResource("/images/logo.png"));
        this.setIconImage(img.getImage());
        
        conn=DataBaseConnection.DBConnection.connectionDB();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allPanel = new javax.swing.JPanel();
        exitPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        lbl_btn = new javax.swing.JLabel();
        lbl_kilit = new javax.swing.JLabel();
        passwordHide = new javax.swing.JCheckBox();
        passwordHideImage = new javax.swing.JLabel();
        textPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        textUserName = new javax.swing.JTextField();
        txt_sifre = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        txt_kullaniciadi = new javax.swing.JLabel();
        txt_grupIsim = new javax.swing.JLabel();
        loginLogo = new javax.swing.JLabel();
        txt_logo = new javax.swing.JLabel();
        sagLogin = new javax.swing.JLabel();
        solLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        allPanel.setBackground(new java.awt.Color(38, 43, 63));
        allPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(allPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        exitPanel.setBackground(new java.awt.Color(38, 43, 63));
        exitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPanelMouseClicked(evt);
            }
        });
        exitPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeBtn.png"))); // NOI18N
        exitPanel.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        getContentPane().add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 60, 60));

        lbl_btn.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        lbl_btn.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn.setText("Giriş");
        getContentPane().add(lbl_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 50, -1));

        lbl_kilit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kilitAnimasyon.gif"))); // NOI18N
        lbl_kilit.setToolTipText("");
        lbl_kilit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lbl_kilit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 320, 250));

        passwordHide.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        passwordHide.setForeground(new java.awt.Color(255, 255, 255));
        passwordHide.setText("Göster/Gizle");
        passwordHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordHideActionPerformed(evt);
            }
        });
        getContentPane().add(passwordHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        passwordHideImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_lock_30px.png"))); // NOI18N
        getContentPane().add(passwordHideImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 30, 40));

        textPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textPassword.setForeground(new java.awt.Color(255, 255, 255));
        textPassword.setText("123");
        textPassword.setBorder(null);
        textPassword.setOpaque(false);
        getContentPane().add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 320, -1));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 320, 10));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 320, 10));

        textUserName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textUserName.setForeground(new java.awt.Color(204, 204, 204));
        textUserName.setText("admin");
        textUserName.setBorder(null);
        textUserName.setOpaque(false);
        textUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textUserNameFocusGained(evt);
            }
        });
        textUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(textUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 410, 40));

        txt_sifre.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        txt_sifre.setForeground(new java.awt.Color(255, 255, 255));
        txt_sifre.setText("Şifre");
        getContentPane().add(txt_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, -1, -1));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonLogo.png"))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, -1, -1));

        txt_kullaniciadi.setBackground(new java.awt.Color(255, 255, 255));
        txt_kullaniciadi.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        txt_kullaniciadi.setForeground(new java.awt.Color(255, 255, 255));
        txt_kullaniciadi.setText("Kullanıcı Adı");
        getContentPane().add(txt_kullaniciadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        txt_grupIsim.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txt_grupIsim.setForeground(new java.awt.Color(255, 255, 255));
        txt_grupIsim.setText("© 2021 All Rights Reserved");
        getContentPane().add(txt_grupIsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 250, 50));

        loginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_Logo.gif"))); // NOI18N
        getContentPane().add(loginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txt_logo.setBackground(new java.awt.Color(255, 255, 255));
        txt_logo.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        txt_logo.setForeground(new java.awt.Color(255, 255, 255));
        txt_logo.setText("Fatura Yönetim Sistemi");
        getContentPane().add(txt_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 410, 80));

        sagLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saglogin.png"))); // NOI18N
        getContentPane().add(sagLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -20, 600, 770));

        solLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/solLogin2.png"))); // NOI18N
        getContentPane().add(solLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 600, 750));

        setSize(new java.awt.Dimension(1143, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitPanelMouseClicked

    private void textUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUserNameActionPerformed

    private void textUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textUserNameFocusGained
        textUserName.setText("admin");
    }//GEN-LAST:event_textUserNameFocusGained

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
         btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonLogo2.png")));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonLogo.png")));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        
        
        String getUserName = textUserName.getText();
        String getPassword = textPassword.getText();
        
        
        
        
        String sql="SELECT * FROM UserAccount WHERE username=? and password=?";
        
        try {
            
           
            pst = conn.prepareStatement(sql);
            pst.setString(1, getUserName);
            pst.setString(2, getPassword);
            
            rs=pst.executeQuery();
            if(rs.next()) {
               
             conn.close();   
             this.setVisible(false);
             new Main.MenuPage(getUserName).setVisible(true);
             
            }
            else {
            JOptionPane.showMessageDialog(null, "Login Unsuccesfull");
                System.out.println(rs.toString());
            
            }
        
        }
        
        catch(Exception ex) {
        
        JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
          // System.out.println("hata bu blokta");
        
        
        }
        
        
    }//GEN-LAST:event_btnLoginMouseClicked

    private void passwordHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordHideActionPerformed
        if (passwordHide.isSelected()) {
            textPassword.setEchoChar((char)0);
            passwordHideImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_unlock_30px.png")));
        }
        else
        {
        
         textPassword.setEchoChar('*');
         passwordHideImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_lock_30px.png")));
        }
    }//GEN-LAST:event_passwordHideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allPanel;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel exitButton;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_btn;
    private javax.swing.JLabel lbl_kilit;
    private javax.swing.JLabel loginLogo;
    private javax.swing.JCheckBox passwordHide;
    private javax.swing.JLabel passwordHideImage;
    private javax.swing.JLabel sagLogin;
    private javax.swing.JLabel solLogin;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUserName;
    private javax.swing.JLabel txt_grupIsim;
    private javax.swing.JLabel txt_kullaniciadi;
    private javax.swing.JLabel txt_logo;
    private javax.swing.JLabel txt_sifre;
    // End of variables declaration//GEN-END:variables
}
